###################
# Songs
###################

[[songs]]
id = 1
name = "BIRDBRAIN"
file = "/<dir>/birdbrain.mp3"
length = 245

[[songs]]
id = 2
name = "strangers once again"
file = "/<dir>/strangers_once_again.mp3"
length = 198

[[songs]]
id = 3
name = "Spoken For"
file = "/<dir>/spoken_for.mp3"
length = 310

[[songs]]
id = 4
name = "Thia Kane"
file = "/<dir>/thia_kane.mp3"
length = 175


###################
# Playlists
###################

[[playlists]]
id = 1
name = "Favourites"
songs = [1, 2]

[[playlists]]
id = 2
name = "Vibing"
songs = [2, 3, 4]
