###################
# Songs
###################

[[songs]]
id = 1
file = "/<dir>/BIRDBRAIN.mp3"
length = 245

[[songs]]
id = 2
file = "/<dir>/strangers_once_again.mp3"
length = 198

[[songs]]
id = 3
file = "/<dir>/Spoken_For.mp3"
length = 310

[[songs]]
id = 4
file = "/<dir>/Thia_Kane.mp3"
length = 175


###################
# Playlists
###################

[[playlists]]
id = 1
name = "Favourites"
songs = [1, 2]

[[playlists]]
id = 2
name = "Vibing"
songs = [2, 3, 4]
